[variables]
HOSTNAME = "0.0.0.0"
PORT = "3000"

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "cp -r public .next/standalone/public || true", "cp -r .next/static .next/standalone/.next/static || true"]

[start]
cmd = "npx prisma migrate deploy && HOSTNAME=0.0.0.0 PORT=3000 node .next/standalone/server.js"
